### ISSUE TITLE
Support 'dry run' mode for local testing

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#655]
## The Problem
Following #550, it would be good to simplify local testing and prevent bugs from causing damage on Mojira.

## Possible Solution
A 'dry run' mode should be added (maybe either as `main` argument, or as `debug` config parameter). When that mode is activated:
- An INFO log message at start should indicate that 'dry run' mode is active.
- Jira credentials become optional (but only when 'dry run' mode is active); when not specified Jira is accessed without authentication.
An INFO log message should indicate that no credentials are specified.
- All actions performing updates on Jira instead only log what they would do (regardless of whether Jira credentials are provided or not).
- All other credentials become optional as well
  - If no language API token is specified the module is not registered (should only be possible in 'dry run' mode?). Additionally an INFO log message should during registration indicate that the module is skipped.
  - The Discord log adapters should be disabled (regardless of whether the webhook URLs are specified). If that is not easily possible, it would also be fine to use malformed webhook URLs, the exception log message would probably be acceptable.

**Comment by violine1101** [comment]
This is essentially blocked by #584. Once that is done, this should be fairly trivial to implement (simply switch out the JIRA backend for one that doesn't change stuff).

**Comment by violine1101** [comment]
Currently I'm using this local config as a workaround for testing things outside of the modules themselves:

```yaml
arisa:
  debug:
    enabledModules:
      - Command
    logOperationNotNeeded: true
    logReturnedIssues: true
    updateLastRun: true
  modules:
    command:
      commandPrefix: $VIOLINEBOT
```
Effectively a dry run, everything except comments starting with `$VIOLINEBOT` will be ignored.
